apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wlnyya914-nodejs 
  janus-idp.io/tekton: wlnyya914-nodejs
  backstage.io/kubernetes-id: wlnyya914-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wlnyya914-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  